journal config recursive definitions

diff --git a/journal b/journal
--- a/journal
+++ b/journal
@@ -3,6 +3,38 @@
 # configuration file
 CONFIG="$HOME/.config/journal2-config.ini"
 
+first-match(){
+	STR="$1" ; shift
+	MATCH="$1" ; shift
+	echo "$STR" | grep -oE "$MATCH" | head -n 1
+}
+
+config-fill(){
+	VAR="$1" ; shift
+	INITIAL="$VAR"
+	while echo "$VAR" | grep --silent '\$' ; do
+		# replace each "${...}" group with it's config value
+
+		# find the "${...}" group, extract the "..."
+		match="$(first-match "$VAR" '\${[^}]+}' )"
+		segment="$(echo $match | tr -d '${}' )"
+
+		if [ `echo $segment | grep -c '.'` -ne 1 ]; then
+			echo "error: can't fill in config value, bad group '$segment' in $INITIAL" > /dev/stderr
+			exit 2
+		fi
+
+		# split into the two parts.
+		front="${segment%%.*}"
+		back="${segment##*.}"
+
+		# go and fetch the parts
+		replace="$(config "$front" "$back")"
+		VAR="$( echo "$VAR" | sed "s_${match}_${replace}_")"
+	done
+	echo "$VAR"
+}
+
 config(){
 	if [ $# -eq 0 ]; then
 		if [ -e "$CONFIG" ]; then
@@ -18,7 +50,7 @@ config(){
 			# not enough arguments are passed.
 			# TODO allow dependent config variables
 			VALUE="$(inifile -f "$CONFIG" -n -s "$SECTION" -k "$KEY")"
-			echo $VALUE | sed "s_\${HOME}_${HOME}_"
+			config-fill "$(echo $VALUE | sed "s_\${HOME}_${HOME}_" )"
 		fi
 	fi
 }
